In [1]:
import torch
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [2]:
block_size = 8
batch_size = 4

In [3]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [4]:
chars = sorted(set(text))

In [5]:
print(chars)
print(len(chars))

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
80


In [6]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}

encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

In [7]:
encoded = encode('ramesh')

In [8]:
encoded

[71, 54, 66, 58, 72, 61]

In [9]:
decode(encoded)

'ramesh'

In [10]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,  1, 47, 33,
        50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0, 26, 49,  0,  0, 36, 11,
         1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,  0,  0, 25, 45, 44, 32, 39,
        42,  1, 39, 30,  1, 44, 32, 29,  1, 47, 33, 50, 25, 42, 28,  1, 39, 30,
         1, 39, 50,  9,  1, 44, 32, 29,  1, 36, 25, 38, 28,  1, 39, 30,  1, 39,
        50,  9,  1, 39, 50, 37, 25,  1, 39, 30])


In [11]:
n = int(0.8*len(data))
n

185828

In [12]:
train_data = data[:n]
val_data = data[n:]

In [13]:
%%time
start_time = time.time()
zeros = torch.zeros(1000,1000)
end_time = time.time()

elapsed_time = end_time - start_time
# print()

CPU times: total: 0 ns
Wall time: 4.99 ms


In [14]:
# Define Probability tensor
probabilities = torch.tensor([0.1, 0.9])

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 0, 1, 0, 1, 1, 1])


In [17]:
tensor = torch.tensor([1,2,3,4,5])
out = torch.cat((tensor, torch.tensor([6])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6])

In [18]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked = torch.stack([tensor1,tensor2,tensor3])
stacked

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([14.1189,  0.2450, -4.0208], grad_fn=<SqueezeBackward4>)


In [21]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])

softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [37]:
for i in tensor1:
    print(i)
    i = 2.71**i
    print(i/29.9)

tensor(1.)
tensor(0.0906)
tensor(2.)
tensor(0.2456)
tensor(3.)
tensor(0.6656)
